Upgrade/ux 1
stacks-network/sbtc-bridge pull request #16
Opened 2024-11-23 23:54 UTC by setbern

toast notifications
- Success of connecting wallet
- Error with connecting wallet
- Success with creating a deposit request
- Error with deposit request
- Error with finding history of your wallet

Faq updates

Styling updates to testnet banner

2024-11-24 08:19 UTC, aldur approved these changes

2024-11-24 08:19 UTC, aldur commented on src/comps/Faqs.tsx
> +          answer="Note: Some aspects of sBTC are still being designed and subject to change. This page will be updated as various elements become finalized. \n sBTC operates by utilizing a synthetic
Where does this text come from?

2024-11-25 14:33 UTC, hozzjss requested changes

2024-11-25 14:33 UTC, hozzjss commented on src/comps/Header.tsx
> +      console.log("userSession.isUserSignedIn()");
should be removed

2024-11-25 14:33 UTC, hozzjss commented on src/comps/Header.tsx
> +      console.log("_events", _events);
should be removed

2024-11-25 14:33 UTC, hozzjss commented on src/comps/NotificationHandler.tsx
why is this file empty?

2024-11-25 14:33 UTC, hozzjss commented on src/comps/Notifications.tsx
General note maybe for the future we could do a refactor, but file names should not be case sensitive CamelCase as some FS's like apple-fs are case insensitive and that would lead to pitfalls on deployments if not careful (dev on macOS and deploy to ubuntu)

2024-11-25 14:33 UTC, hozzjss commented on src/comps/Notifications.tsx
> +    text: "#048848",
not a priority but it's better to define the colors in the tailwind config for reusability and to easily change in the future if needed

2024-11-25 14:33 UTC, hozzjss commented on src/util/atoms.ts
> +  NotificationStatusType,
unused import

2024-11-26 04:03 UTC, setbern commented on src/comps/Header.tsx
> +      console.log("userSession.isUserSignedIn()");
Resovled

2024-11-26 04:03 UTC, setbern commented on src/comps/Header.tsx
> +      console.log("_events", _events);
Removed

2024-11-26 04:03 UTC, setbern commented on src/comps/NotificationHandler.tsx
Deleted

2024-11-26 04:03 UTC, setbern commented on src/util/atoms.ts
> +  NotificationStatusType,
Removed

2024-11-26 15:31 UTC, hozzjss approved these changes
just one comment great work

2024-11-26 15:31 UTC, hozzjss commented on src/comps/Deposit.tsx
> +      console.log("validPrefix", validPrefix);
any reason for this log statement?

2024-11-26 22:53 UTC, merged