feat - get the get-current-aggregate-pubkey
stacks-network/sbtc-bridge pull request #28
Opened 2024-11-27 07:12 UTC by setbern

Ensure the user always has the most recent signer aggregate-pubkey, which is fetched from the clarity contracts.

Heavily depends on environment variables.

2024-11-27 07:16 UTC, setbern commented
Tied to this ticket
https://github.com/stacks-network/sbtc/issues/837

2024-11-27 08:00 UTC, aldur requested changes

2024-11-27 08:00 UTC, aldur commented on src/util/readOnlyHelper.ts
> +    contractName: process.env.NEXT_PUBLIC_SBTC_CONTRACT_NAME || "",
Given that you have the deployer as an env variable, can you use that to fetch the contract removing these two?

Also the sBTC contract name is a constant.

2024-11-27 10:15 UTC, hozzjss requested changes

2024-11-27 10:15 UTC, hozzjss commented on src/comps/Header.tsx
> +import { StacksNetwork, STACKS_TESTNET, STACKS_MAINNET } from "@stacks/network";
`StacksNetwork` is unused

2024-11-27 10:15 UTC, hozzjss commented on src/comps/Header.tsx
> +          });
duplicate logic reuse in a function maybe

2024-11-27 10:15 UTC, hozzjss commented on src/comps/Header.tsx
> +          });
duplicate logic

2024-11-27 10:15 UTC, hozzjss commented on src/comps/Header.tsx
> +          });
duplicate logic

2024-11-27 10:15 UTC, hozzjss commented on src/comps/Header.tsx
> +          });
duplicate logic

2024-11-27 10:15 UTC, hozzjss commented on src/comps/Header.tsx
> +  };
Maybe this would be a good place to integrate a retry logic or use react-query and instead of console.err you could use toast here

2024-11-27 19:25 UTC, setbern commented on src/comps/Header.tsx
> +  hiro: "hiro",
User with the legacy wallet still show hiro as the provider. Example: 
<img width="308" alt="Captura de pantalla 2024-11-27 a la(s) 2 25 10 p m" src="https://github.com/user-attachments/assets/bc56335a-525c-460d-bf38-4fdb26ab1b04">

2024-11-27 19:26 UTC, setbern commented on src/comps/Header.tsx
> +  hiro: "hiro",
This is on firefox with leather version - v6.5.1

2024-11-27 19:26 UTC, setbern commented on src/comps/Header.tsx
> +  hiro: "hiro",
![Captura de pantalla 2024-11-27 a la(s) 2 26 28 p m](https://github.com/user-attachments/assets/e1640722-c644-4307-aa10-ffde2419f08d)

2024-11-29 18:02 UTC, hozzjss commented on src/comps/Header.tsx
> +  hiro: "hiro",
Okay I'd just do a rebase and use the walletInfo atom here

2024-11-29 18:03 UTC, hozzjss commented on src/comps/Header.tsx
> +  };
Here would be a good place to use a server action

2024-12-02 14:28 UTC, setbern commented
This has again become stale and would require more work to catch up then to create a new branch from master and add

2024-12-02 17:47 UTC, aldur approved these changes

2024-12-02 17:47 UTC, aldur commented on src/comps/Deposit.tsx
> +        createReclaimScript(parsedLockTime, new Uint8Array([])),
nit: there's a lot of noise on PRs for this, are our tools using different configs?

2024-12-02 17:48 UTC, hozzjss approved these changes

2024-12-02 17:49 UTC, hozzjss approved these changes

2024-12-02 17:50 UTC, merged